### ISSUE TITLE
Game Crashes on load when randomizer is enabled

### ISSUE THREAD

**Issue by hyperlexus** [mkwcat/nsmbw-pipe-randomizer#1]
just saw your video and tried to play the randomizer, but unfortunately the game crashes.
I'm using Windows 11 with Dolphin Emulator and (stock) riivolution. I downloaded your pack, right click the USA version of NSMBW, start with riivolution patches, and then no matter which randomizer setting I select, the game doesn't work as long as the patch is enabled. the game works without patches, and even works with Newer smbw's riivolution patch (to narrow down the issue).
![image](https://github.com/user-attachments/assets/a2e4092a-fce0-4e40-8147-54e4dc99a05f)
the mod extracted to here in my folder, and the riivolution .xml went into the folder with all the other .xml files (as it should).

When I start the game, it shows the wii safety popup and the "hold your wii remote sideways", and then gives me infinite dolphin panic handlers, which when ignored freeze the game with a blackscreen.
I hope this can be reproduced or there is a simple fix on my side that I can attempt, dual core speedup is off.

**Comment by mkwcat** [comment]
I think I may have found the issue. Can you try using this build from the latest commit?
[NSMBW-Pipe-Randomizer.zip](https://github.com/user-attachments/files/16566258/NSMBW-Pipe-Randomizer.zip)

**Comment by kamden123** [comment]
I have the same issue i used the link you used. only thing i can give is this. its stuck on boot. when i click ok at just changes a few of the numbers on it
![image_2024-08-09_190159483](https://github.com/user-attachments/assets/2aee8974-6446-4692-a16a-bb19c5347a93)

**Comment by kamden123** [comment]
<img width="649" alt="image" src="https://github.com/user-attachments/assets/b11573d6-2fa9-4e82-9f44-b257d283910b">
same thing with the update for me. crashes on boot.

**Comment by fadsasd** [comment]
Wait, it worked?
